[template]
src = "prom-jmx-exporter.yaml.tmpl"
dest = "/opt/prom-jmx-exporter/config.yaml"
keys = [
    "/java/agent/prom-jmx-exporter"
]
reload_cmd = "/opt/minion/confd/scripts/remove-if-empty /opt/prom-jmx-exporter/config.yaml"